sigp/rust-libp2p

protocols/gossipsub/src/layer.rs
protocols/gossipsub/src/layer/tests.rs

The piggybacking mechanism implemented here pools control messages between heartbeats and then coalesces them into `NetworkBehaviourAction::SendEvent` objects before adding them to the `events` queue.
This differs from the Go implementation as I understand it, but should still achieve the desired result of reducing network congestion.
There are also some tests that I wrote a while back in this PR around grafts and prunes.

Piggy backing

---

misc/enr/Cargo.toml
misc/enr/src/lib.rs

Update enr to latest spec from [here](https://eips.ethereum.org/EIPS/eip-778). 
- Change content map from `IndexMap` to `BTreeMap` to get sorted keys.
- Add `ip6`, `tcp6` and `udp6` keys to content map.
- Fix encoding.
- Add test vector from spec

Update enr crate to latest spec

---

misc/discv5/src/behaviour.rs

For the `NODES` response, if the size of the data is greater than `MAX_PACKET_SIZE - 80`, the response is split up into multiple messages. The size check was using the encoding of the `ENR` which did not include the signature on the `ENR` but the encoding which got sent on the wire included the signature in the ENR encoding. 
This resulted in the `NODES` response not getting split up into multiple messages when it should have and caused #9 .
Modify the size check to use the encoding which contains the signature.

Fix size check in `NODES` response to use `.encode().len()` instead of `.size()`

---

misc/discv5/src/behaviour.rs
misc/discv5/src/behaviour/test.rs

I have a few questions on this: 
- Should the `connection_updated` also be called when ENR sequence that was received? Or will this be done when the requested new ENR is returned?
- Could it happen that a PING is received for which no ENR can be found?

Update the DHT on received ping

---

misc/discv5/src/packet/mod.rs
misc/discv5/src/rpc.rs

Add reference tests for all `Packet` types and all `ProtocolMessage` types.
Partially fixes #10

Add reference tests

---

misc/discv5/src/behaviour/test.rs

This test constructs a star topology with `num_nodes` nodes connected to a single bootstrap node. 
The `node_id`s are constructed such that all nodes fall in the 256/255 bucket of the bootstrap node.
Hence, on sending a FINDNODE request for another `target_node` which also falls in the 256/255 buckets, the resulting query should end up finding all the nodes in the network.
Note: `num_nodes` should be less than `k` to guarantee that all nodes are found.

Add test for finding all nodes in star topology

---

protocols/gossipsub/Cargo.toml
protocols/gossipsub/tests/smoke.rs

Implement a basic smoke test that:
1. Builds a fully connected graph of size N.
2. Subscribes each node to the same topic.
3. Publishes a single message.
4. Waits for all nodes to receive the above message.
N and the structure of the graph are reproducibly randomized via
Quickcheck.

protocols/gossipsub: Add basic smoke test

---

examples/gossipsub-chat.rs
protocols/gossipsub/Cargo.toml
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/handler.rs
protocols/gossipsub/src/protocol.rs
protocols/gossipsub/tests/smoke.rs

This moves the `protocols/gossipsub` crate to stable futures along the lines of https://github.com/libp2p/rust-libp2p/pull/1328.
Let's get https://github.com/sigp/rust-libp2p/pull/21 in first and then follow up with this pull request.
Only the last 4 commits are relevant, the remainder is from merging https://github.com/libp2p/rust-libp2p/pull/1328.

protocols/gossipsub: Move to stable futures

---

misc/discv5/src/query_pool/peers/closest.rs

The `on_success` function in `FindNodeQuery` was incorrectly incrementing `peer.peers_returned` by the total closest peers found in the query. It should be incremented by the length of the `closer_peers` found in that invocation of `on_success`. 
However, making this change resulted in peers getting marked as `Failed` when they failed to return > 0 peers after all iterations complete. Not returning any peers shouldn't be a criteria for failure as it's possible that the target node is in some far off bucket relative to the peer. This PR removes the condition that the node should be marked as `Failed` if it returns 0 peers.

[Discv5] Fix bug in FindNode query

---

protocols/gossipsub/src/protocol.rs

Follow up on https://github.com/libp2p/rust-libp2p/pull/1583#discussion_r429733878. Will probably need some adjustments in case signing is moved to `publish_all`.

protocols/gossipsub/src/protocol: Use quickcheck to test signing

---

protocols/gossipsub/src/behaviour.rs

- Make the GossipsubRpc Debug instance a bit nicer by hiding empty fields
- Centralize sending messages to other peers, reducing boilerplate
- Simplify the arc removal code

A few improvements

---

protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/config.rs

The slack backoff is configurable and considered before sending a GRAFT to previously backoffed peers.

improved data structure for storing backoffs + slack backoff

---

protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/lib.rs
protocols/gossipsub/src/mcache.rs
protocols/gossipsub/src/peer_score/mod.rs
protocols/gossipsub/src/peer_score/params.rs
protocols/gossipsub/src/peer_score/tests.rs

calling the score update method hooks + using the score of peers in the behaviour logic

use the score module in the behaviour

---

protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/gossip_promises.rs
protocols/gossipsub/src/lib.rs
protocols/gossipsub/src/peer_score/mod.rs

Most relevant change: Mark gossip promises already as satisfied on receiving a message (without application validation).

Gossipsub v1.1 various improvements

---

examples/gossipsub-chat.rs
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/error.rs
protocols/gossipsub/src/protocol.rs
protocols/gossipsub/src/types.rs

Estimates the RPC message size before publishing. This informs the user if they attempt to publish a message that is over the maximum transmission size.

Estimate message size

---

examples/gossipsub-chat.rs
examples/ipfs-private.rs
protocols/gossipsub/Cargo.toml
protocols/gossipsub/src/backoff.rs
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/handler.rs
protocols/gossipsub/src/lib.rs
protocols/gossipsub/src/types.rs
protocols/gossipsub/tests/smoke.rs

- Shifts the backoff struct into its own module.
- Sets the keep-alive to No for peers that don't suppor the protocol
- Improves debug logs for connecting peers regarding their protocol support
- Takes a topic reference for subscribe/unsubscribe

Cleanup code add logs

---

protocols/gossipsub/Cargo.toml

Removes the unnecessary `lru_time_cache` dependency

Remove lru_time_cache_dep

---

protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/mcache.rs
protocols/gossipsub/src/peer_score/mod.rs
protocols/gossipsub/src/peer_score/params.rs
protocols/gossipsub/src/protocol.rs
protocols/gossipsub/src/time_cache.rs

Various improvements (see single commits for an overview).

Various improvements

---

examples/gossipsub-chat.rs
examples/ipfs-private.rs
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/handler.rs
protocols/gossipsub/src/lib.rs
protocols/gossipsub/src/mcache.rs
protocols/gossipsub/src/peer_score/mod.rs
protocols/gossipsub/src/peer_score/tests.rs
protocols/gossipsub/src/protocol.rs
protocols/gossipsub/src/types.rs

Introduce a generic type used for (decompressed) message data.
Furthermore caches message ids (by using the generic type to store the id within the message data)

use generic type for message data + cache message ids

---

core/src/transport/memory.rs
examples/gossipsub-chat.rs
examples/ipfs-private.rs
protocols/gossipsub/Cargo.toml
protocols/gossipsub/src/backoff.rs
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/gossip_promises.rs
protocols/gossipsub/src/handler.rs
protocols/gossipsub/src/lib.rs
protocols/gossipsub/src/mcache.rs
protocols/gossipsub/src/peer_score.rs
protocols/gossipsub/src/peer_score/mod.rs
protocols/gossipsub/src/protocol.rs
protocols/gossipsub/src/rpc_proto.rs
protocols/gossipsub/src/subscription_filter.rs
protocols/gossipsub/src/time_cache.rs
protocols/gossipsub/src/types.rs
protocols/gossipsub/tests/smoke.rs

Given the size of https://github.com/libp2p/rust-libp2p/pull/1720 I did my review directly inline. A lot of suggestions are just related to styling - I hope delivering my review as a pull request makes accepting those easier. Comments are prefixed with `// mxinden:`.
Let me know if this format works for you. If not, I can transform this into a traditional Github review.
Again, as https://github.com/libp2p/rust-libp2p/pull/1720 is quite large, I have not yet fully reviewed all changes / additions.

protocols/gossipsub: Review

---

protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/metrics.rs

There are 3 primary changes here:
1. The `churn_reason` arg has been added back to `remove_peer_from_mesh()`, though it's now behind the feature flag. This removes an unnecessary redundant lookup to see if the peer is in the mesh and (IMO) makes the code simpler.
2. I've increased the frequency of calling methods on the `InternalMetrics` struct instead of manipulating its members. It looks cleaner now.
3. As an exception to the above, I opted out of calling methods on the `InternalMetrics` in the `heartbeat()` function. By storing a reference to the `MeshSlotData` and interacting with that, you can eliminate up to 4 redundant map lookups per iteration of the main loop over topics. That should be a good cumulative timesave considering this is the heartbeat function.

Cleanup code & Remove Redundant map Lookups

---

Cargo.lock
protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/Cargo.toml
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/handler.rs
protocols/gossipsub/src/types.rs

Gossipsub backpressure

---

protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/protocol.rs
protocols/gossipsub/src/types.rs

feat(gossipsub): remove control pool

---

protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/metrics.rs
protocols/gossipsub/src/types.rs

This gives us visibility on the queue sizes.

Queue metrics

---

protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/handler.rs
protocols/gossipsub/src/types.rs

It is difficult to reason about handler send queues and if in fact they are always in sync with the connected_peer mappings. 
This shifts the send-queues inside the connected_peers mapping to ensure that if there is a connected peer, then it should have a send_queue. 
This prevents any kind of panics that may arise if the send-queue mapping is out of sync with the connected peer mapping. There may still be panics if the connected_peer list is out of sync with mesh or topic mappings, however that is out of scope of this PR. 
As gossipsub has been running for a while, we assume the above mappings are correct.

Couple the send_queue more closely with connected peers

---

Cargo.lock
Cargo.toml
libp2p/CHANGELOG.md
libp2p/Cargo.toml
protocols/gossipsub/CHANGELOG.md
protocols/gossipsub/src/behaviour.rs
protocols/gossipsub/src/behaviour/tests.rs
protocols/gossipsub/src/config.rs
protocols/gossipsub/src/metrics.rs
protocols/gossipsub/src/types.rs
swarm/CHANGELOG.md
swarm/Cargo.toml
swarm/src/behaviour.rs
swarm/src/lib.rs

use only the `connectec_peers` mapping

feat(gossipsub): Remove peer_topics and topic_peers

---

protocols/gossipsub/src/behaviour.rs

This removes all potential panics that can occur due to mismatched connection mappings. It hides them behind an error message in order to debug in the future. 
These panics are not catastrophic and likely have existed for a while.

Remove panics for later debugging

---

protocols/gossipsub/src/behaviour.rs

I believe the fanout was out of sync when peers unsubscribed leading to inconsistent mappings. I think this should correct that.

Correct fanout mapping synchronisation
